#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_


/* for OnOff cluster                    */
#define ZCL_ATTRID_CUSTOM_KEY_LOCK          0xF000
#define ZCL_ATTRID_CUSTOM_LED               0xF001

/* for electrical measurement cluster   */
#define ZCL_ATTRID_CUSTOM_CURRENT_MAX       0xF002
#define ZCL_ATTRID_CUSTOM_POWER_MAX         0xF003
#define ZCL_ATTRID_CUSTOM_TIME_RELOAD       0xF004
#define ZCL_ATTRID_CUSTOM_PROTECT_CONTROL   0xF005
#define ZCL_ATTRID_CUSTOM_AUTORESTART       0xF006
#define ZCL_ATTRID_CUSTOM_ADJUST_CURRENT    0xF007
#define ZCL_ATTRID_CUSTOM_ADJUST_VOLTAGE    0xF008
#define ZCL_ATTRID_CUSTOM_ADJUST_POWER      0xF009

#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
